export const INITIAL_DATA = {
  projects: [
    {
      id: 'proj-mrmikes',
      name: 'MrMikesWeb',
      description: 'Personal website and web presence',
      color: '#3B82F6',
      emoji: '🌐',
      status: 'active',
      links: [
        {
          id: 'link-1',
          label: 'Project Files (OneDrive)',
          url: 'https://onedrive.live.com',
          type: 'files',
          note: 'Source files in OneDrive — update this URL',
        },
        {
          id: 'link-2',
          label: 'Netlify Dashboard',
          url: 'https://app.netlify.com',
          type: 'hosting',
          note: 'Hosted on Netlify',
        },
        {
          id: 'link-3',
          label: 'GitHub Repository',
          url: 'https://github.com',
          type: 'git',
          note: 'Source code — update this URL',
        },
        {
          id: 'link-4',
          label: 'Launch Live Site',
          url: 'https://example.com',
          type: 'live',
          note: 'Update with your actual domain',
        },
      ],
      notes: 'Main personal web project. Update all the URLs above with real ones.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'proj-2',
      name: 'Project 2',
      description: 'Click the pencil to add details and links',
      color: '#8B5CF6',
      emoji: '🚀',
      status: 'active',
      links: [],
      notes: '',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'proj-3',
      name: 'Project 3',
      description: 'Click the pencil to add details and links',
      color: '#10B981',
      emoji: '🛠️',
      status: 'active',
      links: [],
      notes: '',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'proj-4',
      name: 'Project 4',
      description: 'Click the pencil to add details and links',
      color: '#F59E0B',
      emoji: '📱',
      status: 'active',
      links: [],
      notes: '',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'proj-5',
      name: 'Project 5',
      description: 'Click the pencil to add details and links',
      color: '#EC4899',
      emoji: '💡',
      status: 'active',
      links: [],
      notes: '',
      createdAt: new Date().toISOString(),
    },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Add bananas to shopping list',
      category: 'shopping',
      priority: 'low',
      completed: false,
      dueDate: null,
      projectId: null,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-2',
      title: 'Book rental car for vacation',
      category: 'travel',
      priority: 'medium',
      completed: false,
      dueDate: null,
      projectId: null,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-3',
      title: 'Review MrMikesWeb project links and update URLs',
      category: 'work',
      priority: 'high',
      completed: false,
      dueDate: null,
      projectId: 'proj-mrmikes',
      createdAt: new Date().toISOString(),
    },
  ],
  categories: [
    { id: 'shopping', label: 'Shopping', color: '#10B981', emoji: '🛒' },
    { id: 'travel', label: 'Travel', color: '#3B82F6', emoji: '✈️' },
    { id: 'health', label: 'Health', color: '#EF4444', emoji: '❤️' },
    { id: 'work', label: 'Work', color: '#8B5CF6', emoji: '💼' },
    { id: 'personal', label: 'Personal', color: '#F59E0B', emoji: '⭐' },
    { id: 'home', label: 'Home', color: '#06B6D4', emoji: '🏠' },
    { id: 'finance', label: 'Finance', color: '#84CC16', emoji: '💰' },
    { id: 'fitness', label: 'Fitness', color: '#F97316', emoji: '🏃' },
  ],
  bookmarkCategories: [
    { id: 'tech',          label: 'Tech Stuff',     color: '#3B82F6', emoji: '💻' },
    { id: 'cars',          label: 'Car Stuff',      color: '#EF4444', emoji: '🏎️' },
    { id: 'ai',            label: 'AI Stuff',       color: '#8B5CF6', emoji: '🤖' },
    { id: 'dev-tools',     label: 'Dev Tools',      color: '#10B981', emoji: '🛠️' },
    { id: 'learning',      label: 'Learning',       color: '#F59E0B', emoji: '📚' },
    { id: 'uncategorized', label: 'Other',          color: '#6B7280', emoji: '📌' },
  ],
  bookmarks: [
    {
      id: 'bm-1',
      title: 'ChatGPT',
      url: 'https://chat.openai.com',
      description: 'OpenAI chat interface',
      category: 'ai',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bm-2',
      title: 'Claude',
      url: 'https://claude.ai',
      description: 'Anthropic Claude AI',
      category: 'ai',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bm-3',
      title: 'Hacker News',
      url: 'https://news.ycombinator.com',
      description: 'Tech news and discussions',
      category: 'tech',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bm-4',
      title: 'Vercel Dashboard',
      url: 'https://vercel.com/dashboard',
      description: 'Your Vercel deployments',
      category: 'dev-tools',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bm-5',
      title: 'Netlify Dashboard',
      url: 'https://app.netlify.com',
      description: 'Your Netlify sites',
      category: 'dev-tools',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bm-6',
      title: 'GitHub',
      url: 'https://github.com/rob10305',
      description: 'Your GitHub repos',
      category: 'dev-tools',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'bm-7',
      title: 'Bring a Trailer',
      url: 'https://bringatrailer.com',
      description: 'Car auctions and listings',
      category: 'cars',
      createdAt: new Date().toISOString(),
    },
  ],
}
